GET http://localhost:5029/game

###
GET http://localhost:5029/game/4

###
POST http://localhost:5029/game
Content-Type: application/json

{
    "name": "The Legend of Zelda",
    "genreId": "3",
    "price": 59.99,
    "releaseDate": "2017-03-08"
}

###

PUT http://localhost:5029/game/1
Content-Type: application/json

{
    "name": "The Legend of Zelda",
    "genre": "Action-adventure",
    "price": 49.99,
    "releaseDate": "2017-03-08"
}

###
DELETE http://localhost:5029/game/1
